import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = 'sqlite:///' + \
    os.path.join(BASE_DIR, 'database/settings.db')

SQLALCHEMY_TRACK_MODIFICATIONS = False

# Default values for barcodes settings
BARCODES_CAMERA_ID=0
BARCODES_CAMERA_WIDTH=1280
BARCODES_CAMERA_HEIGHT=720
BARCODES_CONTRAST=1.0
BARCODES_BRIGHTNESS=10
BARCODES_AREA_X1=0
BARCODES_AREA_X2=1280
BARCODES_AREA_Y1=0
BARCODES_AREA_Y2=720

# Default values for OMR settings
OMR_BOXES_AREA_X1 = 0
OMR_BOXES_AREA_X2 = 720
OMR_BOXES_AREA_Y1 = 0
OMR_BOXES_AREA_Y2 = 480
OMR_CAMERA_ID = 1
OMR_CAMERA_WIDTH = 1280
OMR_CAMERA_HEIGHT = 720
OMR_CONTRAST = 1.0
OMR_BRIGHTNESS = 10
OMR_BLUR_KENEL_SIZE = 3
OMR_MAX_THRESHOLD = 255
OMR_THRESHOLD_BLOCK_SIZE = 51
OMR_THRESHOLD_C = 10
OMR_BOX_MIN_WIDTH = 1
OMR_BOX_MIN_HEIGHT = 1
OMR_BOX_MIN_ASPECT_RATIO = 0.5
OMR_BOX_MAX_ASPECT_RATIO = 2
OMR_BOXES_PER_ROW = 10
OMR_BOXES_ROWS = 25
OMR_STANDARD_DEVIATION_THRESHOLD = 3